CREATE INDEX idx_device_events_device ON device_events(device_id);;
CREATE INDEX idx_device_events_org    ON device_events(organisation_id);;
CREATE INDEX idx_device_events_type   ON device_events(event_type);;
CREATE INDEX idx_expected_imei ON expected_devices(imei);;
CREATE INDEX idx_expected_manifest ON expected_devices(manifest_id);;
CREATE INDEX idx_expected_org         ON expected_devices(organisation_id);;
CREATE INDEX idx_expected_status ON expected_devices(status);;
CREATE INDEX idx_grade_audit_bulk   ON grade_audit(bulk_id);;
CREATE INDEX idx_grade_audit_device ON grade_audit(received_device_id);;
CREATE INDEX idx_grade_audit_org      ON grade_audit(organisation_id);;
CREATE INDEX idx_manifests_org        ON manifests(organisation_id);;
CREATE UNIQUE INDEX idx_opr_auth_cds ON opr_authorisations(organisation_id, cds_number);;
CREATE INDEX idx_opr_auth_org ON opr_authorisations(organisation_id);;
CREATE INDEX idx_print_jobs_org       ON print_jobs(organisation_id);;
CREATE INDEX idx_print_status ON print_jobs(status);;
CREATE INDEX idx_received_imei     ON received_devices(imei);;
CREATE INDEX idx_received_manifest ON received_devices(manifest_id);;
CREATE INDEX idx_received_org      ON received_devices(organisation_id);;
CREATE INDEX idx_received_sku      ON received_devices(sku);;
CREATE INDEX idx_received_status   ON received_devices(status);;
CREATE INDEX idx_received_supplier ON received_devices(supplier_id);;
CREATE INDEX idx_repair_jobs_device ON repair_jobs(device_id);;
CREATE INDEX idx_repair_jobs_imei   ON repair_jobs(imei);;
CREATE INDEX idx_repair_jobs_org    ON repair_jobs(organisation_id);;
CREATE INDEX idx_repair_jobs_status ON repair_jobs(status);;
CREATE INDEX idx_scan_events_org      ON scan_events(organisation_id);;
CREATE INDEX idx_scan_manifest ON scan_events(manifest_id);;
CREATE INDEX idx_sent_emails_org ON sent_emails(organisation_id);;
CREATE INDEX idx_sent_emails_shipment ON sent_emails(shipment_id);;
CREATE INDEX idx_shipment_lines_device   ON shipment_lines(received_device_id);;
CREATE INDEX idx_shipment_lines_shipment ON shipment_lines(shipment_id);;
CREATE UNIQUE INDEX idx_shipment_lines_unique ON shipment_lines(shipment_id, received_device_id);;
CREATE INDEX idx_shipment_replies_org ON shipment_replies(organisation_id);;
CREATE INDEX idx_shipment_replies_shipment ON shipment_replies(shipment_id);;
CREATE INDEX idx_shipment_value_deltas_org ON shipment_value_deltas(organisation_id);;
CREATE INDEX idx_shipment_value_deltas_shipment ON shipment_value_deltas(shipment_id);;
CREATE INDEX idx_shipments_auth ON shipments(authorisation_id);;
CREATE INDEX idx_shipments_org ON shipments(organisation_id);;
CREATE UNIQUE INDEX idx_shipments_org_ref ON shipments(organisation_id, reference);;
CREATE INDEX idx_sku_brand_model ON sku_catalog(brand, model);;
CREATE INDEX idx_sku_catalog_lookup
  ON sku_catalog(model, capacity, color, grade);;
CREATE INDEX idx_sku_catalog_org      ON sku_catalog(organisation_id);;
CREATE INDEX idx_suppliers_org ON suppliers(organisation_id);;
CREATE INDEX idx_users_org ON users(organisation_id);;
CREATE INDEX idx_webhooks_org ON webhooks(organisation_id);;
CREATE INDEX idx_zoho_batch_devices_batch  ON zoho_batch_devices(batch_id);;
CREATE INDEX idx_zoho_batch_devices_device ON zoho_batch_devices(device_id);;
CREATE UNIQUE INDEX idx_zoho_batch_devices_unique ON zoho_batch_devices(batch_id, device_id);;
CREATE INDEX idx_zoho_batch_events_batch ON zoho_batch_events(batch_id);;
CREATE INDEX idx_zoho_batches_org    ON zoho_batches(organisation_id);;
CREATE INDEX idx_zoho_batches_status ON zoho_batches(status);;
